from pathlib import Path
import json, html

ROOT = Path(__file__).resolve().parents[1]

NAV = [
    ('index.html','Home','home'),
    ('work.html','Work','work'),
    ('experience.html','Experience','experience'),
    ('research.html','Research','research'),
    ('journal.html','Journal','journal'),
    ('contact.html','Contact','contact'),
]

PUBS = [
    ('Transformation and Future Trends of Smart Grid using Machine and Deep Learning.','International Journal of Applied Power Engineering (IJAPE)','Journal article'),
    ('Assessing the Feasibility and Performance of Solar–Wind Hybrid Power Plants in Coastal Areas of Bangladesh: A Techno-Economic Analysis.','Brunei International Conference on Engineering & Technology','Conference paper'),
    ('Sizing an Off-Grid Photovoltaic System for a Regular East African Residence.','IEEE Xplore','Conference paper'),
    ('Optimal Location Selection for Electric Vehicle Charging Points: Advancing Sustainable Urban Development.','10th IEEE International Conference on Power Systems (ICPS)','Conference paper'),
    ('Economic Load Dispatch using the TLBO Algorithm.','IEEE Xplore','Conference paper'),
]

def pic(name, alt, cls='', loading='lazy', original=True):
    ext = 'jpg' if name == 'stage-presentation' else ('jpeg' if name in {
        'about-portrait','research-showcase','project-poster','engineering-workbench','prototype-front','prototype-rear','project-team','team-achievement','fishing-boats','brac-heritage','modern-architecture','lake-greenery','night-alley','rooftop-flowers'
    } else 'png')
    original_path=f'assets/images/originals/{name}.{ext}'
    data=f' data-original="{original_path}"' if original else ''
    return f'''<picture class="{cls}"><source srcset="assets/images/web/{name}.webp" type="image/webp"><img src="{original_path}"{data} alt="{html.escape(alt)}" loading="{loading}" decoding="async"></picture>'''

def header(page):
    nav=''.join(f'<a href="{href}" class="{"is-active" if key==page else ""}">{label}</a>' for href,label,key in NAV)
    return f'''
<a class="skip-link" href="#main-content">Skip to content</a>
<div class="scroll-progress" aria-hidden="true"></div>
<div class="cursor-dot" aria-hidden="true"></div><div class="cursor-ring" aria-hidden="true"><span class="cursor-label"></span></div>
<header class="site-header">
  <a class="brand" href="index.html" aria-label="Khondaker Labib home">
    <span class="brand-mark">KL</span><span class="brand-copy">Khondaker Labib<small>ENGINEERING · PROGRAMMES · GIS</small></span>
  </a>
  <div class="header-right">
    <nav class="site-nav" aria-label="Primary navigation">{nav}</nav>
    <div class="header-actions">
      <button class="icon-btn" type="button" data-sound-open aria-label="Open soundspace" title="Soundspace" data-cursor="Soundspace"><svg viewBox="0 0 24 24"><path d="M5 9v6h4l5 4V5L9 9H5Z"/><path d="M17 9c1.4 1.7 1.4 4.3 0 6"/></svg></button>
      <button class="icon-btn" type="button" data-theme-toggle aria-label="Switch theme" title="Theme"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg></button>
      <button class="icon-btn menu-btn" type="button" aria-expanded="false" aria-label="Open menu"><svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button>
    </div>
  </div>
</header>'''

def footer():
    return '''
<footer class="site-footer">
  <div class="footer-brand"><strong>Khondaker Labib Al Jonayed</strong><p>Engineering project coordination, technical programme delivery, research operations and a growing GIS practice for environment and infrastructure.</p></div>
  <div class="footer-links"><a href="mailto:labibrafi2000@gmail.com">Email</a><a data-config-link="linkedin" target="_blank" rel="noreferrer" hidden>LinkedIn</a><a data-config-link="researchGate" target="_blank" rel="noreferrer" hidden>ResearchGate</a><a data-config-link="githubProfile" target="_blank" rel="noreferrer" hidden>GitHub</a><a data-config-link="playlistUrl" target="_blank" rel="noreferrer" hidden>Playlist</a></div>
  <div class="footer-bottom"><span>© 2026 Khondaker Labib</span><span>Real photographs · No AI imagery</span></div>
</footer>
<div class="soundspace" role="dialog" aria-label="Soundspace">
  <div class="sound-head"><div><span>Soundspace</span><strong>Ambient focus & Labib's YouTube playlist</strong></div><button class="sound-close" type="button" aria-label="Close soundspace">×</button></div>
  <div class="sound-body">
    <div class="audio-row"><button class="audio-play" type="button" aria-label="Play or pause ambient focus audio">▶</button><div class="audio-meta"><strong>Ambient Focus</strong><span>Original website ambience · default off</span></div><span class="audio-time">0:00 / 0:00</span></div>
    <div class="audio-progress" aria-label="Audio progress"><span></span></div>
    <div class="playlist-block"><p>A personal YouTube playlist is connected here. Playback starts only after you choose it.</p><a class="btn btn-secondary" data-playlist-open target="_blank" rel="noreferrer" hidden>Open YouTube playlist ↗</a><iframe class="spotify-frame" title="Labib personal YouTube playlist" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe></div>
  </div>
</div>
<audio id="ambient-audio" preload="metadata" loop src="assets/audio/ambient-focus.wav"></audio>
<div class="lightbox" role="dialog" aria-modal="true" aria-label="Image preview"><div class="lightbox-inner"><button class="lightbox-close" type="button" aria-label="Close image preview">×</button><img src="" alt=""><div class="lightbox-caption"></div></div></div>
<div class="toast" role="status" aria-live="polite"></div>
<script src="assets/js/config.js"></script><script src="assets/js/main.js"></script>'''

def page(title, desc, pagekey, body, canonical):
    return f'''<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title><meta name="description" content="{html.escape(desc)}"><meta name="theme-color" content="#07090c">
<meta property="og:title" content="{html.escape(title)}"><meta property="og:description" content="{html.escape(desc)}"><meta property="og:type" content="website"><meta property="og:image" content="assets/images/og-card.jpg"><meta property="og:url" content="{canonical}">
<meta name="twitter:card" content="summary_large_image"><link rel="canonical" href="{canonical}"><link rel="icon" href="assets/images/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/css/styles.css">
<script type="application/ld+json">{{"@context":"https://schema.org","@type":"Person","name":"Khondaker Labib Al Jonayed","url":"https://labibrafi08.github.io/khondaker-labib-portfolio/","jobTitle":"Engineer — Planning, Marketing & Training","email":"mailto:labibrafi2000@gmail.com","sameAs":["https://github.com/LabibRafi08","https://www.linkedin.com/in/khondaker-labib/","https://www.researchgate.net/profile/Khondaker-Labib-Al-Jonayed?ev=hdr_xprf"],"address":{{"@type":"PostalAddress","addressLocality":"Dhaka","addressCountry":"Bangladesh"}},"alumniOf":[{{"@type":"CollegeOrUniversity","name":"BRAC University"}},{{"@type":"CollegeOrUniversity","name":"Jahangirnagar University"}}]}}</script>
</head><body data-page="{pagekey}">
<div class="page-intro" aria-hidden="true"><div class="intro-inner"><div class="intro-mark"><span>Khondaker Labib</span><span>KL</span></div><div class="intro-line"></div></div></div>
{header(pagekey)}
<main id="main-content">{body}</main>
{footer()}
</body></html>'''

home = f'''
<section class="hero shell">
  <div class="hero-copy">
    <div class="hero-status" data-reveal="left"><span class="status-dot"></span>Dhaka, Bangladesh · Open to global opportunities</div>
    <h1 class="display" data-reveal="left">I turn technical work into <span class="accent">structured delivery.</span></h1>
    <p class="lead" data-reveal="left">I am an engineering professional working across project planning, technical programme delivery, industry engagement and research operations—now extending that systems background into GIS for environment, infrastructure and urban development.</p>
    <div class="role-line" data-reveal="left"><span class="role-chip"><strong>Current role:</strong> Engineer — Planning, Marketing & Training</span><span class="role-chip"><strong>Graduate study:</strong> MSc in GIS for Environment & Development</span></div>
    <div class="button-row" data-reveal="left"><a class="btn btn-primary" data-magnetic data-cursor="Explore work" href="work.html">Explore selected work <svg viewBox="0 0 24 24"><path d="M5 12h14M14 6l6 6-6 6"/></svg></a><a class="btn btn-secondary" data-magnetic data-cursor="Open CV" href="assets/docs/Khondaker_Labib_Al_Jonayed_CV.pdf" download>Download CV</a><a class="btn btn-secondary" data-config-link="githubProfile" data-cursor="GitHub" target="_blank" rel="noreferrer" hidden>GitHub</a></div>
  </div>
  <div class="hero-visual" data-reveal="right" data-tilt>
    <figure class="hero-image-wrap">{pic('hero-convocation','Khondaker Labib in a blue graduation gown, leaning beside a railing', loading='eager')}<figcaption class="hero-image-label"><span>Electrical & Electronic Engineering</span><strong>BRAC University</strong></figcaption></figure>
    <div class="float-card float-a"><span>Professional centre</span><strong>Engineering + organised execution</strong></div>
    <div class="float-card float-b"><span>Current direction</span><strong>GIS · Infrastructure · Development</strong></div>
  </div>
</section>
<section class="proof-bar" aria-label="Professional focus"><div class="proof-track"><span>Engineering Project Coordination</span><i></i><span>Technical Programme Delivery</span><i></i><span>Research Operations</span><i></i><span>Industry Engagement</span><i></i><span>GIS for Environment & Infrastructure</span><i></i><span>Engineering Project Coordination</span><i></i><span>Technical Programme Delivery</span><i></i><span>Research Operations</span><i></i><span>Industry Engagement</span><i></i><span>GIS for Environment & Infrastructure</span><i></i></div></section>
<section class="section shell">
  <div class="section-head" data-reveal><div><p class="kicker">Professional evidence</p><h2 class="h2">Work measured by outcomes, not adjectives.</h2></div><p class="lead">The numbers below come from delivered technical programmes and institutional outreach at FaboTronix—not generic skill claims.</p></div>
  <div class="metric-grid">
    <article class="metric" data-reveal><strong data-count="10" data-suffix="+">0</strong><span>Technical training programmes delivered</span><small>IoT · Robotics · PLC</small></article>
    <article class="metric" data-reveal><strong data-count="20" data-suffix="+">0</strong><span>Hands-on workshops delivered</span><small>Practical engineering learning</small></article>
    <article class="metric" data-reveal><strong data-count="150" data-suffix="+">0</strong><span>Participants trained directly</span><small>Structured technical sessions</small></article>
    <article class="metric" data-reveal><strong data-count="35" data-suffix="+">0</strong><span>Polytechnic institutes reached</span><small>800+ students engaged</small></article>
  </div>
</section>
<section class="section shell">
  <div class="story-grid">
    <figure class="story-photo" data-reveal="left">{pic('about-portrait','Khondaker Labib in a traditional outfit on a tree-lined road')}<figcaption>Personal portrait — included to introduce the person behind the work, not as decoration.</figcaption></figure>
    <div class="story-copy" data-reveal="right"><p class="kicker">Professional profile</p><h2 class="h2">At the centre of my work is execution.</h2><div class="prose"><p>I coordinate the people, information, resources and communication required to move a technical objective from idea to delivery. My experience spans hands-on engineering programmes, institutional engagement, product and R&D support, research administration and applied technology projects.</p><p>My electrical and electronic engineering background helps me understand systems, sensors and implementation constraints. My current MSc in GIS is widening that perspective toward spatial analysis, sustainable infrastructure, urban systems and disaster-risk decision support.</p></div><div class="story-points"><div class="story-point"><span>01</span><div><strong>Technical understanding</strong><p>EEE, IoT, sensors, automation, energy systems and hardware-centred prototyping.</p></div></div><div class="story-point"><span>02</span><div><strong>Delivery discipline</strong><p>Planning, documentation, stakeholder coordination, training operations and measurable follow-through.</p></div></div><div class="story-point"><span>03</span><div><strong>Spatial direction</strong><p>Developing GIS capability for infrastructure, environment, urban development and risk analysis.</p></div></div></div></div>
  </div>
</section>
<section class="section shell">
  <div class="section-head" data-reveal><div><p class="kicker">Selected evidence</p><h2 class="h2">Images and words tell the same story.</h2></div><p class="lead">Each visual below is directly connected to the work being described: project showcase, programme presentation and urban-environment observation.</p></div>
  <div class="case-grid">
    <a class="case-card featured" href="work.html#knitting-machine" data-reveal="left" data-tilt data-cursor="Open case">{pic('research-showcase','Project team presenting the circular knitting machine monitoring prototype')}<div class="case-copy"><span>Featured engineering project</span><h3>Performance monitoring and predictive maintenance for a circular knitting machine</h3><p>IoT-enabled condition monitoring using ESP32, sensors, dashboard development and machine-learning analysis.</p><b>Read the complete case study ↗</b></div></a>
    <a class="case-card" href="experience.html#fabotronix" data-reveal="right" data-tilt data-cursor="Experience">{pic('stage-presentation','Khondaker Labib presenting a technical programme on stage')}<div class="case-copy"><span>Programme delivery</span><h3>Technical training, outreach and industry engagement</h3><p>Planning and communicating practical programmes across students, institutes and industry partners.</p><b>View professional evidence ↗</b></div></a>
    <a class="case-card" href="research.html#gis-direction" data-reveal="right" data-tilt data-cursor="GIS direction">{pic('urban-water','Urban water and drainage condition observed from a building')}<div class="case-copy"><span>Current GIS direction</span><h3>Environment, infrastructure and urban systems</h3><p>Building spatial-analysis capability around flood, drainage, accessibility, risk and sustainable development.</p><b>Explore the research direction ↗</b></div></a>
  </div>
</section>
<section class="process-band"><div class="section shell process-wrap">
  <div data-reveal="left"><p class="kicker">How I work</p><h2 class="h2">Technical depth matters when it can be organised and delivered.</h2><p class="lead" style="margin-top:22px">My contribution is strongest where engineering understanding must be converted into a practical plan, coordinated implementation and documented outcome.</p><div class="button-row"><a class="text-link" href="experience.html">See the full professional timeline <span>↗</span></a></div></div>
  <div class="process-list"><article class="process-item" data-reveal><span>01</span><div><h3>Clarify the operating problem</h3><p>Define the user, context, constraints, evidence and success criteria before proposing a solution.</p></div></article><article class="process-item" data-reveal><span>02</span><div><h3>Structure the delivery plan</h3><p>Translate the objective into tasks, ownership, resources, timelines and documentation.</p></div></article><article class="process-item" data-reveal><span>03</span><div><h3>Coordinate people and systems</h3><p>Keep technical work, communication, logistics and stakeholder expectations aligned.</p></div></article><article class="process-item" data-reveal><span>04</span><div><h3>Validate and communicate the outcome</h3><p>Review performance, capture evidence, report clearly and improve the next delivery cycle.</p></div></article></div>
</div></section>
<section class="section shell" id="direction">
  <div class="direction-grid">
    <div data-reveal="left"><p class="kicker">Current graduate direction</p><h2 class="h2">Building an engineering–GIS profile for environment and infrastructure.</h2><p class="lead" style="margin-top:24px">My MSc in GIS for Environment and Development is extending my systems background into spatial analysis, urban development, disaster risk, flood and drainage, transport, utilities and evidence-based infrastructure planning.</p><div class="pills"><span class="pill">Spatial analysis</span><span class="pill">Remote sensing</span><span class="pill">Urban systems</span><span class="pill">Disaster risk</span><span class="pill">Flood & drainage</span><span class="pill">Infrastructure GIS</span></div><a class="btn btn-secondary" data-magnetic href="research.html" data-cursor="Research">Explore research and GIS</a></div>
    <div class="direction-gallery" data-reveal="right"><figure>{pic('green-facade','Green facade and contemporary architecture under a cloudy sky')}<figcaption>Built environment and climate-responsive architecture</figcaption></figure><figure>{pic('urban-water','Urban water and drainage condition')}<figcaption>Urban drainage and environmental pressure</figcaption></figure><figure>{pic('storm-city','Storm clouds over a dense urban area')}<figcaption>Urban climate and exposure</figcaption></figure></div>
  </div>
</section>
<section class="section shell">
  <div class="section-head" data-reveal><div><p class="kicker">Research communication</p><h2 class="h2">Selected publications.</h2></div><p class="lead">Work across smart grids, renewable-energy systems, EV infrastructure and optimisation—presented without inflated claims or invented metrics.</p></div>
  <div class="publication-list">{''.join(f'<article class="publication" data-reveal><span class="num">0{i}</span><div><h3>{html.escape(t)}</h3><p>{html.escape(v)}</p></div><span class="tag">{html.escape(tag)}</span></article>' for i,(t,v,tag) in enumerate(PUBS[:3],1))}</div>
  <div class="button-row"><a class="btn btn-secondary" href="research.html">View all publications and research</a></div>
</section>
<section class="section shell">
  <div class="section-head" data-reveal><div><p class="kicker">Visual journal</p><h2 class="h2">Observation as a supporting practice.</h2></div><p class="lead">A tightly curated selection from my own archive—architecture, urban atmosphere and coastal landscapes. The journal supports the portfolio; it does not compete with the professional work.</p></div>
  <div class="journal-grid"><a class="journal-card tall" href="journal.html" data-reveal="left" data-cursor="Open journal">{pic('green-facade','Vertical greenery on a contemporary building')}<span><strong>Built environment</strong><small>Architecture, climate and vertical greenery</small></span></a><a class="journal-card" href="journal.html" data-reveal data-cursor="Open journal">{pic('storm-city','Storm cloud over a dense city')}<span><strong>Urban weather</strong><small>Atmosphere over Dhaka</small></span></a><a class="journal-card" href="journal.html" data-reveal data-cursor="Open journal">{pic('sea-sunset','Sunset reflected across the sea')}<span><strong>Coastal light</strong><small>Horizon and movement</small></span></a><a class="journal-card wide" href="journal.html" data-reveal="right" data-cursor="Open journal">{pic('brac-heritage','Historic red-brick university architecture')}<span><strong>Institutional architecture</strong><small>Material, history and place</small></span></a></div>
</section>
<section class="section shell"><div class="cta" data-reveal><div><p class="kicker">Contact</p><h2 class="h2">Need someone who can connect technical work with organised delivery?</h2></div><div class="button-row"><a class="btn btn-primary" data-magnetic href="contact.html">Start a conversation</a><a class="btn btn-secondary" href="mailto:labibrafi2000@gmail.com">Email directly</a></div></div></section>
'''

work = f'''
<section class="page-hero shell"><div><p class="kicker">Selected work</p><h1 class="display">Evidence before <span class="accent">presentation.</span></h1><p class="lead" style="margin-top:26px">Detailed project and programme case studies showing the problem, my contribution, technical stack, implementation process and evidence.</p></div><aside class="page-hero-aside"><div><span>Primary case study</span><strong>Industrial predictive maintenance</strong></div><div><span>Project mode</span><strong>Engineering · Research · Programme delivery</strong></div><div><span>Code links</span><strong>Shown automatically when configured</strong></div></aside></section>
<section class="section shell" id="knitting-machine">
  <div class="case-study-hero"><div data-reveal="left"><p class="kicker">Featured engineering case study</p><h2 class="h2">Performance monitoring and analysis for predictive maintenance of a circular knitting machine.</h2><div class="prose" style="margin-top:25px"><p>Unplanned machine downtime can interrupt production and increase maintenance cost. This final-year design project explored an IoT-enabled monitoring system that collects machine-condition data, presents critical parameters on a dashboard and supports predictive-maintenance analysis.</p><p>The project combined embedded hardware, data acquisition, communication and analytical work. The result was demonstrated through a physical prototype, project poster and live showcase.</p></div><div class="case-facts"><div class="case-fact"><span>Context</span><strong>Final Year Design Project</strong></div><div class="case-fact"><span>Institution</span><strong>BRAC University</strong></div><div class="case-fact"><span>Completed</span><strong>May 2025</strong></div><div class="case-fact"><span>Core technologies</span><strong>ESP32 · IoT · Python · MATLAB/Simulink</strong></div></div><div class="button-row"><a class="btn btn-primary" data-config-link="knittingProjectRepository" target="_blank" rel="noreferrer" hidden>View repository ↗</a><a class="btn btn-secondary" href="assets/docs/Khondaker_Labib_Al_Jonayed_CV.pdf" download>Project in CV</a></div></div>
  <div class="case-mosaic" data-reveal="right"><figure>{pic('research-showcase','Project team presenting the circular knitting machine monitoring prototype')}<figcaption>Live project showcase</figcaption></figure><figure>{pic('project-poster','Technical poster for the circular knitting machine monitoring project')}<figcaption>System poster and analysis</figcaption></figure><figure>{pic('prototype-front','Front view of the embedded project prototype')}<figcaption>Embedded prototype hardware</figcaption></figure></div></div>
</section>
<section class="section-compact shell"><p class="kicker" data-reveal>System architecture</p><h2 class="h2" data-reveal>From machine condition to maintenance decision.</h2><div class="architecture-flow"><article class="flow-node" data-reveal><span>01 · Source</span><strong>Machine condition</strong><p>Operating parameters and physical-condition signals from the knitting machine.</p></article><article class="flow-node" data-reveal><span>02 · Sensing</span><strong>Industrial sensors</strong><p>Condition variables are measured and converted into usable electrical signals.</p></article><article class="flow-node" data-reveal><span>03 · Edge</span><strong>ESP32 controller</strong><p>Embedded acquisition, local processing and communication.</p></article><article class="flow-node" data-reveal><span>04 · Visibility</span><strong>Monitoring dashboard</strong><p>Critical machine parameters presented for real-time observation.</p></article><article class="flow-node" data-reveal><span>05 · Analysis</span><strong>Predictive support</strong><p>Python and MATLAB-based analysis to support maintenance planning.</p></article></div></section>
<section class="section shell"><div class="section-head" data-reveal><div><p class="kicker">My contribution</p><h2 class="h2">What I actually worked on.</h2></div><p class="lead">This section separates verified contribution from general team ownership.</p></div><div class="detail-grid"><article class="detail-card" data-reveal><h3>System development</h3><ul><li>Contributed to the IoT-enabled condition-monitoring architecture.</li><li>Integrated ESP32-based hardware with sensing and communication elements.</li><li>Supported testing and prototype refinement.</li></ul></article><article class="detail-card" data-reveal><h3>Dashboard and analysis</h3><ul><li>Built a dashboard for monitoring critical machine parameters.</li><li>Used Python and MATLAB/Simulink within the analysis workflow.</li><li>Supported the predictive-maintenance decision concept.</li></ul></article><article class="detail-card" data-reveal><h3>Research communication</h3><ul><li>Structured the project story for poster and live presentation.</li><li>Documented the system architecture, workflow and results.</li><li>Explained the prototype to visitors during the showcase.</li></ul></article><article class="detail-card" data-reveal><h3>Engineering workflow</h3><ul><li>Worked across hardware, software and presentation requirements.</li><li>Coordinated tasks within a multidisciplinary student team.</li><li>Connected technical implementation with a practical industrial problem.</li></ul></article></div></section>
<section class="section-compact shell"><div class="section-head" data-reveal><div><p class="kicker">Physical evidence</p><h2 class="h2">Prototype, test bench and team presentation.</h2></div><p class="lead">These are original project photographs, used only where they directly document the work.</p></div><div class="evidence-grid"><figure data-reveal>{pic('engineering-workbench','Testing workbench with sensors, meters and embedded hardware')}<figcaption>Hardware testing and integration workbench</figcaption></figure><figure data-reveal>{pic('prototype-rear','Rear view of the embedded electronics prototype')}<figcaption>Prototype assembly and interconnection</figcaption></figure><figure data-reveal>{pic('project-team','Project team with prototype and monitoring display')}<figcaption>Team presentation with the completed prototype</figcaption></figure></div></section>
<section class="process-band" id="safe-fall"><div class="section shell process-wrap"><div data-reveal="left"><p class="kicker">Research operations case</p><h2 class="h2">Safe Fall Dataset.</h2><div class="prose" style="margin-top:22px"><p>At the Biomedical Science and Engineering Research Center, I led the operational development of a human fall-detection dataset using sensors and cameras for AI-based healthcare applications.</p><p>My role focused on turning a research objective into a repeatable data-collection workflow through planning, hardware setup and coordination.</p></div></div><div class="process-list"><article class="process-item" data-reveal><span>01</span><div><h3>Project planning</h3><p>Structured activities, responsibilities and data-collection requirements.</p></div></article><article class="process-item" data-reveal><span>02</span><div><h3>Hardware setup</h3><p>Coordinated sensor and camera arrangements required for collection.</p></div></article><article class="process-item" data-reveal><span>03</span><div><h3>Data collection</h3><p>Supported consistent execution and documentation of sessions.</p></div></article><article class="process-item" data-reveal><span>04</span><div><h3>Research coordination</h3><p>Connected researchers, logistics and operational requirements.</p></div></article></div></div></section>
<section class="section shell" id="programme-delivery"><div class="story-grid"><figure class="story-photo" data-reveal="left">{pic('stage-presentation','Khondaker Labib presenting a technical programme on stage')}<figcaption>Technical programme communication and participant engagement.</figcaption></figure><div class="story-copy" data-reveal="right"><p class="kicker">Programme delivery case</p><h2 class="h2">Technical learning designed around practical participation.</h2><div class="prose"><p>At FaboTronix, I support the planning, communication and delivery of programmes in IoT, robotics and PLC. The work combines technical content, participant acquisition, institutional partnerships and operational follow-through.</p></div><div class="story-points"><div class="story-point"><span>10+</span><div><strong>Training programmes</strong><p>Structured technical learning delivered with practical components.</p></div></div><div class="story-point"><span>20+</span><div><strong>Workshops</strong><p>Short-format technical sessions for students and aspiring engineers.</p></div></div><div class="story-point"><span>35+</span><div><strong>Institutes reached</strong><p>Institutional outreach engaging more than 800 students.</p></div></div></div><a class="text-link" href="experience.html#fabotronix">See the complete experience <span>↗</span></a></div></div></section>
'''

experience = f'''
<section class="page-hero shell"><div><p class="kicker">Professional experience</p><h1 class="display">Technical understanding, <span class="accent">organised delivery.</span></h1><p class="lead" style="margin-top:26px">A professional timeline focused on responsibilities, evidence and outcomes—not rewritten CV filler.</p></div><aside class="page-hero-aside"><div><span>Current employer</span><strong>FaboTronix Limited</strong></div><div><span>Previous organisation</span><strong>BIOSE, BRAC University</strong></div><div><span>Professional centre</span><strong>Coordination · Training · Research operations</strong></div></aside></section>
<section class="section shell"><div class="timeline">
  <article class="timeline-item" id="fabotronix"><div class="timeline-head"><div><h2>Engineer — Planning, Marketing & Training</h2><p>FaboTronix Limited · Dhaka, Bangladesh</p></div><div class="timeline-date">Nov 2025 — Present</div></div><div class="timeline-body"><div class="timeline-copy"><ul><li>Delivered 10 technical training programmes and 20 workshops in IoT, robotics and PLC, training more than 150 participants.</li><li>Expanded institutional engagement by reaching 800+ students across 35 polytechnic institutes and recruiting 150+ industrial-attachment participants.</li><li>Supported partnerships with more than 10 industry organisations.</li><li>Contributed to strategic marketing, technical content, participant acquisition, product development, R&D, laboratory setup and cross-functional engineering operations.</li></ul></div><figure class="timeline-photo">{pic('stage-presentation','Khondaker Labib presenting a technical programme')} </figure></div></article>
  <article class="timeline-item"><div class="timeline-head"><div><h2>Administrative Coordinator</h2><p>Biomedical Science and Engineering Research Center · BRAC University</p></div><div class="timeline-date">Apr 2024 — Nov 2025</div></div><div class="timeline-body no-photo"><div class="timeline-copy"><ul><li>Coordinated research operations including procurement, logistics, documentation and stakeholder communication.</li><li>Supported project execution by working with researchers, academic leadership and external partners.</li><li>Managed administrative processes required for efficient delivery of multidisciplinary research initiatives.</li><li>Led the operational development of the Safe Fall Dataset through planning, hardware setup and data-collection coordination.</li></ul></div></div></article>
</div></section>
<section class="section-compact shell"><div class="section-head" data-reveal><div><p class="kicker">Capability map</p><h2 class="h2">What the experience has built.</h2></div><p class="lead">A broad profile with a clear centre: technical work organised into deliverable programmes, projects and research operations.</p></div><div class="skills-grid"><article class="skill-card" data-reveal><span>01</span><h3>Project coordination</h3><p>Requirements, task planning, ownership, timelines, stakeholder alignment and documentation.</p></article><article class="skill-card" data-reveal><span>02</span><h3>Technical programme delivery</h3><p>Training structure, workshop operations, participant engagement and hands-on implementation.</p></article><article class="skill-card" data-reveal><span>03</span><h3>Industry & institutional engagement</h3><p>Outreach, partnerships, communication and education–industry connection.</p></article><article class="skill-card" data-reveal><span>04</span><h3>Research operations</h3><p>Procurement, logistics, data-collection coordination, technical documentation and reporting.</p></article><article class="skill-card" data-reveal><span>05</span><h3>Engineering tools</h3><p>MATLAB, PVsyst, HOMER, Proteus, Python, IoT, robotics and hardware prototyping.</p></article><article class="skill-card" data-reveal><span>06</span><h3>Spatial development tools</h3><p>ArcGIS, Google Earth Engine and a developing remote-sensing and spatial-analysis practice.</p></article></div></section>
<section class="process-band"><div class="section shell"><div class="section-head" data-reveal><div><p class="kicker">Education</p><h2 class="h2">Engineering foundation, spatial direction.</h2></div><p class="lead">The academic path explains the interdisciplinary profile rather than making it look scattered.</p></div><div class="detail-grid"><article class="detail-card" data-reveal><h3>MSc in GIS for Environment and Development</h3><p>Jahangirnagar University · Aug 2025 — Present</p><p>Current focus: spatial analysis, environment, urban systems and sustainable infrastructure.</p></article><article class="detail-card" data-reveal><h3>BSc in Electrical and Electronic Engineering</h3><p>BRAC University · May 2020 — May 2025</p><p>Foundation in electronics, sensors, power systems, embedded technology and engineering design.</p></article></div></div></section>
<section class="section shell"><div class="section-head" data-reveal><div><p class="kicker">Leadership & community</p><h2 class="h2">Communication, visual direction and field coordination.</h2></div><p class="lead">Included as supporting evidence of leadership—not presented as a substitute for professional work.</p></div><div class="detail-grid"><article class="detail-card" data-reveal><h3>Director, Graphics and Photography</h3><p>BRAC University Electrical & Electronic Club · Dec 2024 — Jan 2026</p><p>Directed visual branding, event materials and media coverage for technical and student-engagement activities.</p></article><article class="detail-card" data-reveal><h3>Field volunteering</h3><p>Healing Bangladesh and Hopelamp · 2024 — 2025</p><p>Supported community rehabilitation, outreach, logistics, resource distribution and volunteer coordination.</p></article></div></section>
'''

research = f'''
<section class="page-hero shell"><div><p class="kicker">Research & GIS</p><h1 class="display">Applied research, <span class="accent">spatial direction.</span></h1><p class="lead" style="margin-top:26px">Research projects and publications grounded in engineering, energy, sensing and a growing interest in GIS for environment, infrastructure and urban systems.</p></div><aside class="page-hero-aside"><div><span>Current degree</span><strong>MSc in GIS for Environment & Development</strong></div><div><span>Research style</span><strong>Applied · interdisciplinary · evidence-oriented</strong></div><div><span>Future domain</span><strong>Infrastructure, risk, water and urban systems</strong></div></aside></section>
<section class="section shell" id="gis-direction"><div class="direction-grid"><div data-reveal="left"><p class="kicker">Current academic direction</p><h2 class="h2">From sensors and systems to place-based decision support.</h2><div class="prose" style="margin-top:24px"><p>My EEE background has trained me to think in systems: inputs, signals, constraints, interactions and measurable performance. GIS adds the spatial dimension—where problems occur, who is affected and how infrastructure or environmental conditions vary across place.</p><p>I am developing this combined perspective for flood and drainage management, transport and infrastructure GIS, disaster-risk assessment, utility and asset management, urban development and environmental monitoring.</p></div><div class="pills"><span class="pill">ArcGIS</span><span class="pill">Google Earth Engine</span><span class="pill">Remote sensing</span><span class="pill">Spatial analysis</span><span class="pill">Urban systems</span><span class="pill">Disaster risk</span></div></div><div class="direction-gallery" data-reveal="right"><figure>{pic('green-facade','Green architecture and vertical vegetation')}<figcaption>Sustainable built environment</figcaption></figure><figure>{pic('urban-water','Urban water and drainage condition')}<figcaption>Flood and drainage systems</figcaption></figure><figure>{pic('storm-city','Storm clouds over dense urban development')}<figcaption>Urban climate and risk</figcaption></figure></div></div></section>
<section class="section-compact shell"><div class="section-head" data-reveal><div><p class="kicker">Research portfolio</p><h2 class="h2">Projects with clear roles.</h2></div><p class="lead">No unrelated photographs are used to imply work that was not documented.</p></div><div class="detail-grid"><article class="detail-card" data-reveal><h3>Predictive maintenance for a circular knitting machine</h3><p>IoT-enabled condition monitoring with ESP32, sensors, a monitoring dashboard and analytical support using Python and MATLAB/Simulink.</p><a class="text-link" href="work.html#knitting-machine">Read the case study <span>↗</span></a></article><article class="detail-card" data-reveal><h3>Safe Fall Dataset</h3><p>Project lead for an AI-healthcare dataset using sensors and cameras. Responsibilities included planning, hardware setup and data-collection coordination.</p><a class="text-link" href="work.html#safe-fall">Read the case study <span>↗</span></a></article></div></section>
<section class="section shell"><div class="section-head" data-reveal><div><p class="kicker">Publications</p><h2 class="h2">Energy, power systems and sustainable infrastructure.</h2></div><p class="lead">Publication titles and venues are reproduced from the CV. Author-position and citation metrics are intentionally not invented.</p></div><div class="publication-list">{''.join(f'<article class="publication" data-reveal><span class="num">0{i}</span><div><h3>{html.escape(t)}</h3><p>{html.escape(v)}</p></div><span class="tag">{html.escape(tag)}</span></article>' for i,(t,v,tag) in enumerate(PUBS,1))}</div></section>
<section class="process-band"><div class="section shell"><div class="section-head" data-reveal><div><p class="kicker">GIS portfolio roadmap</p><h2 class="h2">Projects to build next—clearly labelled as in development.</h2></div><p class="lead">These are not presented as completed analyses. They define the evidence needed to strengthen the GIS side of the portfolio.</p></div><div class="research-focus-grid"><article class="research-focus" data-reveal>{pic('urban-water','Urban drainage and water condition')}<div><span>In development</span><h3>Urban flood and drainage assessment</h3><p>Susceptibility, drainage condition, exposure and decision-support mapping.</p></div></article><article class="research-focus" data-reveal>{pic('terrace-cityscape','Dense urban development and sky')}<div><span>In development</span><h3>Transport and infrastructure accessibility</h3><p>Network-based accessibility and service-coverage analysis.</p></div></article><article class="research-focus" data-reveal>{pic('green-facade','Green building facade')}<div><span>In development</span><h3>Sustainable infrastructure suitability</h3><p>Multi-criteria spatial assessment for resilient development.</p></div></article></div></div></section>
'''

journal_items = [
 ('green-facade','Built environment','Architecture, climate and vertical greenery','architecture'),
 ('modern-architecture','Modern structure','Concrete, pattern and planted edges','architecture'),
 ('brac-heritage','Institutional heritage','Red brick, craft and campus history','architecture'),
 ('framed-city','Framed city','Urban scale seen through architectural edges','urban'),
 ('urban-water','Urban water','Drainage, density and environmental pressure','urban'),
 ('storm-city','Storm over the city','Weather, exposure and dense development','urban'),
 ('terrace-cityscape','Terrace horizon','Urban atmosphere and changing light','urban'),
 ('night-alley','Night alley','A narrow urban passage after dark','urban'),
 ('cloudscape','Cloud study','Light and volume above the city','environment'),
 ('street-tree','Street tree','Nature, infrastructure and the urban horizon','environment'),
 ('lake-greenery','Lake and greenery','Water, vegetation and quiet space','environment'),
 ('rooftop-flowers','Rooftop flowers','Small ecology within the built environment','environment'),
 ('fishing-boats','Fishing boats','Coastal livelihood and colour','coast'),
 ('sea-sunset','Sea sunset','Horizon, movement and evening light','coast'),
 ('architecture-night','Architecture at night','Light, shadow and structure','architecture'),
]
items_html=''.join(f'''<figure class="gallery-item" data-category="{cat}" data-reveal data-cursor="View image">{pic(name,cap)}<figcaption class="gallery-caption"><strong>{title}</strong><span>{cap}</span></figcaption></figure>''' for name,title,cap,cat in journal_items)
journal = f'''
<section class="page-hero shell"><div><p class="kicker">Visual journal</p><h1 class="display">Observation, <span class="accent">carefully curated.</span></h1><p class="lead" style="margin-top:26px">Original photographs from my own archive. The selection is limited to images that support themes of architecture, urban systems, environment and coastal landscapes.</p></div><aside class="page-hero-aside"><div><span>Image source</span><strong>Personal archive only</strong></div><div><span>AI treatment</span><strong>None</strong></div><div><span>Full-resolution originals</span><strong>Preserved in the website package</strong></div></aside></section>
<section class="section shell"><div class="section-head" data-reveal><div><p class="kicker">Curated collection</p><h2 class="h2">Fewer images, stronger relationships.</h2></div><p class="lead">Each photograph has a purpose and caption. Casual duplicates and unrelated personal memories are excluded from the professional narrative.</p></div><div class="filter-row" role="group" aria-label="Filter photography"><button class="filter-btn is-active" data-filter="all">All</button><button class="filter-btn" data-filter="architecture">Architecture</button><button class="filter-btn" data-filter="urban">Urban systems</button><button class="filter-btn" data-filter="environment">Environment</button><button class="filter-btn" data-filter="coast">Coast</button></div><div class="gallery">{items_html}</div></section>
'''

contact = f'''
<section class="page-hero shell"><div><p class="kicker">Contact</p><h1 class="display">Let’s discuss work with <span class="accent">clear outcomes.</span></h1><p class="lead" style="margin-top:26px">Open to engineering-project coordination, technical programme delivery, research operations and GIS-led environment or infrastructure opportunities.</p></div><aside class="page-hero-aside"><div><span>Based in</span><strong>Dhaka, Bangladesh</strong></div><div><span>Email</span><strong>labibrafi2000@gmail.com</strong></div><div><span>Response route</span><strong>Direct email or configured form</strong></div></aside></section>
<section class="section shell"><div class="contact-grid"><figure class="contact-portrait" data-reveal="left">{pic('field-portrait','Khondaker Labib seated outdoors beside an open field')}<figcaption class="contact-note"><strong>Khondaker Labib Al Jonayed</strong><span>Engineer · Programme Delivery · Research Operations · GIS</span></figcaption></figure><div data-reveal="right"><p class="kicker">Start a conversation</p><h2 class="h2">Share the context, problem and expected outcome.</h2><p class="lead" style="margin-top:22px">That helps me understand whether the conversation concerns an engineering project, programme collaboration, research operation or GIS opportunity.</p><div class="contact-methods"><a class="contact-method" href="mailto:labibrafi2000@gmail.com"><span>Email</span><strong>labibrafi2000@gmail.com</strong></a><a class="contact-method" href="tel:+8801766912830"><span>Phone</span><strong>+880 1766-912830</strong></a><a class="contact-method" data-config-link="linkedin" target="_blank" rel="noreferrer" hidden><span>Professional network</span><strong>LinkedIn ↗</strong></a><a class="contact-method" data-config-link="researchGate" target="_blank" rel="noreferrer" hidden><span>Research profile</span><strong>ResearchGate ↗</strong></a></div><form class="contact-form" id="contact-form"><div class="form-grid"><div class="field"><label for="name">Name</label><input id="name" name="name" autocomplete="name" required></div><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="email" required></div></div><div class="field"><label for="subject">Subject</label><input id="subject" name="subject" required></div><div class="field"><label for="message">Message</label><textarea id="message" name="message" required></textarea></div><div class="button-row"><button class="btn btn-primary" type="submit" data-magnetic>Prepare message</button><a class="btn btn-secondary" href="assets/docs/Khondaker_Labib_Al_Jonayed_CV.pdf" download>Download CV</a></div></form></div></div></section>
'''

pages = {
 'index.html': page('Khondaker Labib — Engineering Projects, Programme Delivery & GIS','Portfolio of Khondaker Labib Al Jonayed: engineering project coordination, technical programme delivery, research operations and GIS for environment and infrastructure.','home',home,'https://labibrafi08.github.io/khondaker-labib-portfolio/'),
 'work.html': page('Selected Work — Khondaker Labib','Engineering and programme case studies by Khondaker Labib, including IoT-enabled predictive maintenance and research operations.','work',work,'https://labibrafi08.github.io/khondaker-labib-portfolio/work.html'),
 'experience.html': page('Experience — Khondaker Labib','Professional experience in technical programme delivery, institutional engagement, research operations and engineering coordination.','experience',experience,'https://labibrafi08.github.io/khondaker-labib-portfolio/experience.html'),
 'research.html': page('Research & GIS — Khondaker Labib','Research projects, publications and GIS interests in environment, infrastructure, urban systems and disaster risk.','research',research,'https://labibrafi08.github.io/khondaker-labib-portfolio/research.html'),
 'journal.html': page('Visual Journal — Khondaker Labib','Curated original photography focused on architecture, urban systems, environment and coastal landscapes.','journal',journal,'https://labibrafi08.github.io/khondaker-labib-portfolio/journal.html'),
 'contact.html': page('Contact — Khondaker Labib','Contact Khondaker Labib for engineering projects, programme collaboration, research operations and GIS opportunities.','contact',contact,'https://labibrafi08.github.io/khondaker-labib-portfolio/contact.html'),
}
for name, content in pages.items():
    (ROOT/name).write_text(content,encoding='utf-8')

# Compatibility redirect from old URL.
(ROOT/'projects.html').write_text('''<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=work.html"><link rel="canonical" href="work.html"><title>Redirecting…</title></head><body><p>Redirecting to <a href="work.html">Selected Work</a>.</p></body></html>''',encoding='utf-8')
(ROOT/'photography.html').write_text('''<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=journal.html"><link rel="canonical" href="journal.html"><title>Redirecting…</title></head><body><p>Redirecting to <a href="journal.html">Visual Journal</a>.</p></body></html>''',encoding='utf-8')

# Simple 404.
body404='''<section class="page-hero shell"><div><p class="kicker">404</p><h1 class="display">This page is <span class="accent">not here.</span></h1><p class="lead" style="margin-top:26px">The link may be outdated or the page may have moved.</p><div class="button-row"><a class="btn btn-primary" href="index.html">Return home</a><a class="btn btn-secondary" href="contact.html">Contact</a></div></div></section>'''
(ROOT/'404.html').write_text(page('Page not found — Khondaker Labib','The requested portfolio page could not be found.','404',body404,'https://labibrafi08.github.io/khondaker-labib-portfolio/404.html'),encoding='utf-8')

# Config/data docs.
(ROOT/'content'/'site-content.json').write_text(json.dumps({
  'name':'Khondaker Labib Al Jonayed',
  'headline':'I turn technical work into structured delivery.',
  'role':'Engineer — Planning, Marketing & Training',
  'location':'Dhaka, Bangladesh',
  'email':'labibrafi2000@gmail.com',
  'phone':'+880 1766-912830',
  'metrics':{'training_programmes':'10+','workshops':'20+','participants_trained':'150+','institutes_reached':'35+','students_engaged':'800+'},
  'publications':[{'title':t,'venue':v,'type':tag} for t,v,tag in PUBS]
},indent=2),encoding='utf-8')

# Build script copy for transparency.
(ROOT/'scripts'/'build.py').write_text(Path(__file__).read_text(),encoding='utf-8')
